version: '3'
services:
  postgres:
    image: postgres:9.6

  mysql:
    image: mysql:5.6.24
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  redis:
    image: redis:2.8.19

  rails_master:
    build: .
    depends_on:
      - postgres
      - mysql
      - redis
